### ISSUE TITLE
No Buildings in the Tabs

### ISSUE THREAD

**Issue by MrAtoni** [t1a2l/BetterEducationToolbar#1]
No buildings show up in any of the school tabs. Not even the campus tabs.

I have tried reloading the game.

[output_log.txt](https://github.com/t1a2l/BetterEducationToolbar/files/8765825/output_log.txt)

![BetterEducationToolbar1](https://user-images.githubusercontent.com/16511737/170121915-85f618a3-38ed-4fcb-926a-6d94ee99a693.jpg)
![BetterEducationToolbar2](https://user-images.githubusercontent.com/16511737/170121918-af724e09-7ec2-459a-a227-d1ff27d9632a.jpg)
![BetterEducationToolbar3](https://user-images.githubusercontent.com/16511737/170121919-10cec795-2629-4155-a9ba-d69c6655b5b5.jpg)

**Comment by chameleon-tbn** [comment]
You have various ``NullReferenceException`` Errors in your Log. Can be caused by Missing assets/dependencies, broken assets, broken other mods or even wrong Loading Order.

Please check your latest LSM _report_ File and also CompatibilityReport.txt ... And If you use Load Order Mod Tool, Take Care to Reset Order after you subscribe new mods

**Comment by dbhawk42** [comment]
I had the same issue where the buildings were not showing in the toolbar.  It's been discovered that having this mod and Network Extensions enabled causes this issue.  Disabling NXt2 in content manager fixed the buildings not showing up.

**Comment by mdziubak** [comment]
I have the same issue. Buildings not showing in the toolbar. I have Network Extensions 2 too.
